-- Canonical public market-event ledger. Browsers can read recent events but
-- only the signed server publisher can insert or update them.
create table if not exists public.market_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  event_type text not null,
  event_time timestamptz not null,
  icon text not null,
  title text not null,
  detail text not null,
  tone text not null default 'gold',
  symbol text,
  side text,
  price numeric,
  amount_usd numeric,
  importance smallint not null default 50,
  is_highlight boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint market_events_key_length check (char_length(event_key) between 5 and 120),
  constraint market_events_type_allowed check (event_type in ('liquidation','jackpot','whale','candle','breakout','macro')),
  constraint market_events_text_lengths check (
    char_length(icon) between 1 and 12 and
    char_length(title) between 3 and 80 and
    char_length(detail) between 5 and 240
  ),
  constraint market_events_tone_allowed check (tone in ('up','dn','gold')),
  constraint market_events_symbol_length check (symbol is null or char_length(symbol) between 2 and 20),
  constraint market_events_side_allowed check (side is null or side in ('long','short','buy','sell','up','down')),
  constraint market_events_price_valid check (price is null or price > 0),
  constraint market_events_amount_valid check (amount_usd is null or amount_usd >= 0),
  constraint market_events_importance_valid check (importance between 0 and 100),
  constraint market_events_metadata_size check (pg_column_size(metadata) <= 4096)
);

create index if not exists market_events_time_idx on public.market_events (event_time desc);
create index if not exists market_events_liquidation_time_idx
  on public.market_events (event_time desc) where event_type in ('liquidation','jackpot');

alter table public.market_events enable row level security;
drop policy if exists market_events_public_read on public.market_events;
create policy market_events_public_read on public.market_events
  for select to anon, authenticated
  using (event_time >= now() - interval '48 hours');

revoke all on table public.market_events from public, anon, authenticated, service_role;
revoke all on sequence public.market_events_id_seq from public, anon, authenticated, service_role;
grant select on table public.market_events to anon, authenticated, service_role;
grant insert, update on table public.market_events to service_role;
grant usage, select on sequence public.market_events_id_seq to service_role;

create or replace function public.set_market_event_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
revoke all on function public.set_market_event_updated_at() from public, anon, authenticated;
grant execute on function public.set_market_event_updated_at() to service_role;

drop trigger if exists market_events_updated_at on public.market_events;
create trigger market_events_updated_at
before update on public.market_events
for each row execute function public.set_market_event_updated_at();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'market_events'
  ) then
    alter publication supabase_realtime add table public.market_events;
  end if;
end $$;
