-- Private operational health ledger. Only the signed Edge Function may write.
create table if not exists public.ops_health_logs (
  id bigint generated by default as identity primary key,
  sample_key text not null unique,
  observed_at timestamptz not null,
  host_name text not null,
  overall_status text not null,
  uptime_seconds bigint not null,
  load_1m numeric(8,3) not null,
  cpu_usage_pct numeric(5,2) not null,
  memory_available_mb integer not null,
  swap_used_mb integer not null,
  root_disk_used_pct numeric(5,2) not null,
  disk_read_kbps numeric(14,2),
  disk_write_kbps numeric(14,2),
  disk_busy_pct numeric(5,2),
  cpu_temp_c numeric(5,2),
  gpu_temp_c numeric(5,2),
  gpu_util_pct numeric(5,2),
  main_bot_ok boolean not null,
  main_bot_heartbeat_at timestamptz,
  signal_candle timestamptz,
  signal_regime text,
  signal_target text,
  bithumb_timer_ok boolean not null,
  bithumb_last_exit_code smallint,
  bithumb_account_1_aligned boolean,
  bithumb_account_2_aligned boolean,
  issues text[] not null default '{}'::text[],
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint ops_health_sample_key_length check (char_length(sample_key) between 8 and 120),
  constraint ops_health_host_name_length check (char_length(host_name) between 1 and 63),
  constraint ops_health_status_allowed check (overall_status in ('healthy', 'degraded', 'critical')),
  constraint ops_health_uptime_valid check (uptime_seconds >= 0),
  constraint ops_health_load_valid check (load_1m >= 0),
  constraint ops_health_cpu_valid check (cpu_usage_pct between 0 and 100),
  constraint ops_health_memory_valid check (memory_available_mb >= 0 and swap_used_mb >= 0),
  constraint ops_health_disk_valid check (
    root_disk_used_pct between 0 and 100 and
    (disk_read_kbps is null or disk_read_kbps >= 0) and
    (disk_write_kbps is null or disk_write_kbps >= 0) and
    (disk_busy_pct is null or disk_busy_pct between 0 and 100)
  ),
  constraint ops_health_temperatures_valid check (
    (cpu_temp_c is null or cpu_temp_c between -50 and 150) and
    (gpu_temp_c is null or gpu_temp_c between -50 and 150) and
    (gpu_util_pct is null or gpu_util_pct between 0 and 100)
  ),
  constraint ops_health_signal_valid check (
    (signal_regime is null or signal_regime in ('RISK_ON', 'RISK_OFF')) and
    (signal_target is null or signal_target in ('ETH', 'USDT'))
  ),
  constraint ops_health_issues_valid check (cardinality(issues) <= 32),
  constraint ops_health_details_size check (pg_column_size(details) <= 16384)
);

create index if not exists ops_health_logs_observed_at_idx
  on public.ops_health_logs (observed_at desc);
create index if not exists ops_health_logs_status_time_idx
  on public.ops_health_logs (overall_status, observed_at desc);

alter table public.ops_health_logs enable row level security;
revoke all on table public.ops_health_logs from public, anon, authenticated, service_role;
revoke all on sequence public.ops_health_logs_id_seq from public, anon, authenticated, service_role;
grant select, insert, update on table public.ops_health_logs to service_role;
grant usage, select on sequence public.ops_health_logs_id_seq to service_role;

do $$
declare
  existing_job bigint;
begin
  select jobid into existing_job
  from cron.job
  where jobname = 'ops-health-retention-90d';
  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;
  perform cron.schedule(
    'ops-health-retention-90d',
    '17 3 * * *',
    $job$delete from public.ops_health_logs where observed_at < now() - interval '90 days'$job$
  );
end $$;
